[telegram]
token = "TELEGRAM_TOKEN"
polling_timeout_seconds = 30

[scrapper]
base_url = "http://localhost:8080"
timeout_seconds = 10

[server]
host = "0.0.0.0"
port = 8081

[database]
dsn = "postgresql://bot:bot@localhost:5433/bot"
access-type = "SQL"  # "SQL" or "ORM"

[notification]
transport = "kafka"  # "http" or "kafka"

[notification.kafka]
bootstrap_servers = "localhost:9094"
topic = "link-updates"
group_id = "bot-service"
